version: '3'
services:
  cloud-service-center:
    image: yangguiyun/cloud-service-center
    ports:
      - "1988:1988"
  cloud-config-server:
    image: yangguiyun/cloud-config-server
    ports:
      - "8888:8888"
  cloud-service-provider:
    image: yangguiyun/cloud-service-provider
    ports:
      - "1992:1992"
  cloud-api-gateway:
    image: yangguiyun/cloud-api-gateway
    ports:
      - "1987:1987"
  cloud-service-consumer:
    image: yangguiyun/cloud-service-consumer
    ports:
      - "1986:1986"