server:
  port: 1981
spring:
  application:
    name: cloud-config-client
  cloud:
    config:
      uri: localhost:1980 # config server
      name: cloud-config # 要读取的配置文件application属性
      profile: ${config.profile:dev} # default config profile